[package]
name = "wrap_tests"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.2.1", features = [ "unstable", ] }
blst = { path = "../../..", features = [ "no-threads" ] }
