[package]
name = "risc0-wrapper-methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "1.2.1", features = [ "unstable", ] }

[package.metadata.risc0]
methods = ["guest"]
